'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),WebSocket=require('ws');
const PORT=process.env.PORT||3000,HOST='0.0.0.0',MAX=20,TICK=50,ROUND=180,HP=100,SPEED=5;
const maps={cyber:{name:'Cyber City',w:1600,h:900},factory:{name:'Abandoned Factory',w:1600,h:900},jungle:{name:'Jungle Arena',w:1600,h:900}};
const weapons={pulse:{damage:18,cool:700,speed:12},plasma:{damage:30,cool:1100,speed:9}};const rooms=new Map();
const send=(ws,o)=>{if(ws?.readyState===WebSocket.OPEN)try{ws.send(JSON.stringify(o))}catch{}};
const broadcast=(r,o)=>{send(r.host,o);r.players.forEach(p=>send(p.ws,o))};
function name(v){return typeof v==='string'?v.replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,20):''}
function code(){let c='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';for(let k=0;k<500;k++){let x='';for(let i=0;i<4;i++)x+=c[crypto.randomInt(c.length)];if(!rooms.has(x))return x}return null}
function uniq(r,n){let s=new Set([...r.players.values()].map(p=>p.name.toLowerCase()));if(!s.has(n.toLowerCase()))return n;for(let i=2;i<1000;i++){let x=(n.slice(0,20-String(i).length-3)+' ('+i+')');if(!s.has(x.toLowerCase()))return x}return n}
function spawn(r,i){let m=maps[r.map],cols=5;return{x:150+(i%cols)*((m.w-300)/4),y:150+Math.floor(i/cols)*180}}
function pub(p){return{id:p.id,name:p.name,x:Math.round(p.x),y:Math.round(p.y),hp:p.hp,alive:p.alive,kills:p.kills,weapon:p.weapon}}
function state(r){return{type:'state',phase:r.phase,map:r.map,mapName:maps[r.map].name,width:maps[r.map].w,height:maps[r.map].h,remaining:r.phase==='playing'?Math.max(0,Math.ceil((r.ends-Date.now())/1000)):0,players:[...r.players.values()].map(pub),projectiles:r.bullets.map(b=>({id:b.id,x:Math.round(b.x),y:Math.round(b.y)}))}}
function board(r){return[...r.players.values()].map(p=>({name:p.name,kills:p.kills,hp:p.hp,alive:p.alive})).sort((a,b)=>b.kills-a.kills||b.hp-a.hp)}
function reset(p,r,i){let s=spawn(r,i);Object.assign(p,{...s,hp:HP,alive:true,kills:0,weapon:'pulse',lastM:0,lastS:0,lastD:0,input:{up:false,down:false,left:false,right:false},angle:0})}
function start(r){r.phase='playing';r.ends=Date.now()+ROUND*1000;r.bullets=[];let i=0;r.players.forEach(p=>reset(p,r,i++));broadcast(r,{type:'matchStart',map:r.map,mapName:maps[r.map].name,duration:ROUND});r.timer=setInterval(()=>tick(r),TICK)}
function finish(r,reason){if(r.phase==='ended')return;r.phase='ended';clearInterval(r.timer);let rank=[...r.players.values()].map(p=>({name:p.name,kills:p.kills,alive:p.alive})).sort((a,b)=>b.kills-a.kills||Number(b.alive)-Number(a.alive));broadcast(r,{type:'matchEnd',reason,ranking:rank});broadcast(r,state(r))}
function hit(r,a,t,d){if(!t.alive)return;t.hp-=d;if(t.hp<=0){t.hp=0;t.alive=false;if(a&&a!==t)a.kills++;send(t.ws,{type:'eliminated',respawnIn:2000});setTimeout(()=>{if(r.phase==='playing'&&r.players.has(t.id)){let s=spawn(r,Math.floor(Math.random()*10));Object.assign(t,s,{hp:HP,alive:true})}},2000)}}
function dist(a,b,c,d){return Math.hypot(a-c,b-d)}
function tick(r){if(r.phase!=='playing')return;let m=maps[r.map],now=Date.now();r.players.forEach(p=>{if(!p.alive)return;let x=(p.input.right?1:0)-(p.input.left?1:0),y=(p.input.down?1:0)-(p.input.up?1:0);if(x||y){let l=Math.hypot(x,y);p.x+=x/l*SPEED;p.y+=y/l*SPEED}p.x=Math.max(18,Math.min(m.w-18,p.x));p.y=Math.max(18,Math.min(m.h-18,p.y))});let nb=[];for(const b of r.bullets){b.x+=Math.cos(b.a)*b.speed;b.y+=Math.sin(b.a)*b.speed;if(b.x<0||b.y<0||b.x>m.w||b.y>m.h)continue;let hitit=false;for(const t of r.players.values()){if(!t.alive||t.id===b.owner)continue;if(dist(b.x,b.y,t.x,t.y)<=26){hit(r,r.players.get(b.owner),t,b.damage);hitit=true;break}}if(!hitit)nb.push(b)}r.bullets=nb;if(now>=r.ends)return finish(r,'TIME UP');if(now-r.last>100){r.last=now;broadcast(r,state(r));send(r.host,{type:'hostBoard',players:board(r)})}}
function create(ws,msg){if(ws.ctx)return;let n=name(msg.name);if(!n)return send(ws,{type:'error',message:'Enter your name.'});let c=code();if(!c)return send(ws,{type:'error',message:'Server busy.'});let r={code:c,host:ws,hostName:n,players:new Map(),next:1,map:'cyber',phase:'lobby',ends:0,bullets:[],timer:null,last:Date.now()};rooms.set(c,r);ws.ctx={role:'host',room:r};send(ws,{type:'created',role:'host',code:c,name:n,max:MAX,maps})}
function join(ws,msg){if(ws.ctx)return;let c=typeof msg.code==='string'?msg.code.trim().toUpperCase():'';let n=name(msg.name),r=rooms.get(c);if(!/^[A-Z0-9]{4}$/.test(c)||!n)return send(ws,{type:'error',message:'Enter your name and 4-digit room code.'});if(!r)return send(ws,{type:'error',message:'Room not found.'});if(r.players.size>=MAX)return send(ws,{type:'error',message:'Room is full.'});if(r.phase==='ended')return send(ws,{type:'error',message:'Match has ended.'});let id=r.next++,p={id,name:uniq(r,n),ws,x:100,y:100,hp:HP,alive:true,kills:0,weapon:'pulse',lastM:0,lastS:0,lastD:0,input:{up:false,down:false,left:false,right:false},angle:0};r.players.set(id,p);ws.ctx={role:'player',room:r,id};send(ws,{type:'joined',role:'player',code:c,id,name:p.name,max:MAX,map:r.map});send(ws,state(r));if(r.phase==='playing')send(ws,{type:'lateJoin',message:'Joined live match — fight from now!'});broadcast(r,state(r))}
function input(ws,m){let c=ws.ctx,p=c?.room?.players.get(c?.id);if(!p||!p.alive)return;p.input={up:!!m.input?.up,down:!!m.input?.down,left:!!m.input?.left,right:!!m.input?.right};if(Number.isFinite(m.angle))p.angle=m.angle}
function melee(ws){let c=ws.ctx,r=c?.room,p=r?.players.get(c?.id);if(!p||!p.alive||r.phase!=='playing'||Date.now()-p.lastM<450)return;p.lastM=Date.now();for(const t of r.players.values())if(t.id!==p.id&&t.alive&&dist(p.x,p.y,t.x,t.y)<=70){let d=Math.atan2(t.y-p.y,t.x-p.x),q=Math.atan2(Math.sin(d-p.angle),Math.cos(d-p.angle));if(Math.abs(q)<=Math.PI*.75)hit(r,p,t,22)}}
function shoot(ws){let c=ws.ctx,r=c?.room,p=r?.players.get(c?.id);if(!p||!p.alive||r.phase!=='playing')return;let w=weapons[p.weapon],now=Date.now();if(now-p.lastS<w.cool)return;p.lastS=now;r.bullets.push({id:crypto.randomUUID(),owner:p.id,x:p.x+Math.cos(p.angle)*25,y:p.y+Math.sin(p.angle)*25,a:p.angle,speed:w.speed,damage:w.damage})}
function dash(ws){let c=ws.ctx,r=c?.room,p=r?.players.get(c?.id);if(!p||!p.alive||r.phase!=='playing'||Date.now()-p.lastD<1200)return;p.lastD=Date.now();let m=maps[r.map];p.x=Math.max(18,Math.min(m.w-18,p.x+Math.cos(p.angle)*72));p.y=Math.max(18,Math.min(m.h-18,p.y+Math.sin(p.angle)*72))}
function msg(ws,m){switch(m.type){case'create':return create(ws,m);case'join':return join(ws,m);case'map':if(ws.ctx?.role==='host'&&ws.ctx.room.phase==='lobby'&&maps[m.map]){ws.ctx.room.map=m.map;broadcast(ws.ctx.room,{type:'mapChanged',map:m.map,mapName:maps[m.map].name})}return;case'start':if(ws.ctx?.role==='host'){let r=ws.ctx.room;if(r.phase==='lobby'&&r.players.size)start(r)}return;case'input':return input(ws,m);case'melee':return melee(ws);case'shoot':return shoot(ws);case'dash':return dash(ws);case'weapon':{let p=ws.ctx?.room?.players.get(ws.ctx?.id);if(p&&weapons[m.weapon])p.weapon=m.weapon;return}}}
function close(ws){let c=ws.ctx;if(!c)return;let r=c.room;ws.ctx=null;if(c.role==='host'){clearInterval(r.timer);rooms.delete(r.code);r.players.forEach(p=>send(p.ws,{type:'roomClosed',message:'Host left the room.'}));return}r.players.delete(c.id);if(r.phase==='playing')broadcast(r,state(r))}
const files={'/':'index.html','/index.html':'index.html','/game.js':'game.js','/style.css':'style.css'};
const server=http.createServer((req,res)=>{let u=(req.url||'/').split('?')[0];if(u==='/healthz'){res.writeHead(200,{'Content-Type':'text/plain'});return res.end('ok')}let f=files[u];if(!f){res.writeHead(404);return res.end('Not found')}fs.readFile(path.join(__dirname,'public',f),(e,d)=>{if(e){res.writeHead(500);return res.end('File unavailable')}let t=f.endsWith('.html')?'text/html':f.endsWith('.js')?'text/javascript':'text/css';res.writeHead(200,{'Content-Type':t+'; charset=utf-8','Cache-Control':'no-cache'});res.end(d)})});
const wss=new WebSocket.Server({server,maxPayload:8192,perMessageDeflate:false});wss.on('connection',ws=>{ws.ctx=null;ws.on('message',d=>{try{let m=JSON.parse(d);if(m&&typeof m.type==='string')msg(ws,m)}catch{send(ws,{type:'error',message:'Invalid message.'})}});ws.on('close',()=>close(ws))});server.listen(PORT,HOST,()=>console.log('Battle Arena listening on '+HOST+':'+PORT));
